### PR TITLE
Use _results_number=0 in the Socorro query

### PR DESCRIPTION
**Pull request by marco-c**
The values in 'hits' are unused, so using _results_number=0 will speed up the query.

### CODE REVIEW

**Comment by ashughes1** [comment]
@marco-c I tested this locally and I'm finding the performance is actually degraded, 0.006s longer and 0.096s longer with _results_number=0, cached and no cache respectively, despite having a 18.07KB smaller payload. This was tested with the Network performance tool in Firefox 57 with results averaged across 10 testruns.

Data for _results_number=0 testrun:
```
js     267.93 KB  93.48 KB  0.30 s
css    144.00 KB  29.69 KB  0.59 s
xhr     23.12 KB    0.00 KB   0.00 s
```

Data for a testrun without _results_number=0:
```
js     267.93 KB  93.48 KB  0.04 s
css    144.00 KB  29.69 KB  0.10 s
xhr      5.05 KB   0.00 KB  0.00 s
```
Any thoughts on these results? Are you able to replicate similar locally?

**Comment by adngdb** [comment]
No idea, no. It is counterintuitive that demanding no results is slower. I have no idea what could be involved in there. What I'm sure though is that you're still requiring less bandwidth, which is still a win, especially for such a small decrease in response time.

**Comment by marco-c** [comment]
> Any thoughts on these results? Are you able to replicate similar locally?

I hadn't actually looked at the raw numbers there, now I have.
I see that the difference in timing is for js/css requests, which is unrelated to this change. So I guess the measurements are just too noisy to make sense.

**Comment by ashughes1** [comment]
I added _results_number=0 to the query along with the fix for issue #18. The time increase is perplexing but minimal and the data load is reduced. I'm closing this issue, will address the iframe size separately.

**Comment by marco-c** [comment]
Thanks!

**Pull request closed without merging**
