### PR TITLE
Increase size of the chart, to make it more readable.

### LINKED ISSUE #8: Make the chart bigger
It's 300x150 now, it'd be more readable if it was bigger.

### PR DESCRIPTION
**Pull request by marco-c**
Fixes #8.

### CODE REVIEW

**Comment by marco-c** [comment]
ping @ashughes1

**Comment by ashughes1** [comment]
Hi @marco-c, I'm sorry it's taking me so long to get to this but Bugzilla Socorro Lens is just a side project of mine. Since it is not part of my official work at Mozilla it will take a back seat to those professional projects which are of higher priority. I also have a situation in my personal life that is occupying most of my non-work time. This is why I emphasized in my blog post that I would *not* be accepting pull requests and preferred people contribute ideas which I would then implement on my own time.

I appreciate your effort in trying to make this a better tool and will get to your PRs in time. Unfortunately due to present circumstances in my life I will not be able to _immediately_ respond to this or other PRs submitted. Rest assured I am aware of it and will get to it when I can.

I apologize for any inconvenience this causes but I trust you accept it with dignity and respect. 

Thank you

**Comment by marco-c** [comment]
Of course! I hadn't read your blog post, otherwise I wouldn't have submitted the PRs.

Thanks for the addon by the way, it's great!

**Comment by marco-c** [comment]
This was recently fixed, thanks!

**Pull request closed without merging**
